# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/anaconda/anaconda3/envs/test10/lib/python3.10/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /Users/anaconda/anaconda3/envs/test10/lib/python3.10/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jaebeomlee/Documents/Codes/cuTAGI

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jaebeomlee/Documents/Codes/cuTAGI

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Users/anaconda/anaconda3/envs/test10/lib/python3.10/site-packages/cmake/data/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/anaconda/anaconda3/envs/test10/lib/python3.10/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jaebeomlee/Documents/Codes/cuTAGI/CMakeFiles /Users/jaebeomlee/Documents/Codes/cuTAGI//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jaebeomlee/Documents/Codes/cuTAGI/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cutagi_lib

# Build rule for target.
cutagi_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cutagi_lib
.PHONY : cutagi_lib

# fast build rule for target.
cutagi_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/build
.PHONY : cutagi_lib/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named cutagi

# Build rule for target.
cutagi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cutagi
.PHONY : cutagi

# fast build rule for target.
cutagi/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi.dir/build.make CMakeFiles/cutagi.dir/build
.PHONY : cutagi/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

src/activation_fun_cpu.o: src/activation_fun_cpu.cpp.o
.PHONY : src/activation_fun_cpu.o

# target to build an object file
src/activation_fun_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/activation_fun_cpu.cpp.o
.PHONY : src/activation_fun_cpu.cpp.o

src/activation_fun_cpu.i: src/activation_fun_cpu.cpp.i
.PHONY : src/activation_fun_cpu.i

# target to preprocess a source file
src/activation_fun_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/activation_fun_cpu.cpp.i
.PHONY : src/activation_fun_cpu.cpp.i

src/activation_fun_cpu.s: src/activation_fun_cpu.cpp.s
.PHONY : src/activation_fun_cpu.s

# target to generate assembly for a file
src/activation_fun_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/activation_fun_cpu.cpp.s
.PHONY : src/activation_fun_cpu.cpp.s

src/common.o: src/common.cpp.o
.PHONY : src/common.o

# target to build an object file
src/common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/common.cpp.o
.PHONY : src/common.cpp.o

src/common.i: src/common.cpp.i
.PHONY : src/common.i

# target to preprocess a source file
src/common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/common.cpp.i
.PHONY : src/common.cpp.i

src/common.s: src/common.cpp.s
.PHONY : src/common.s

# target to generate assembly for a file
src/common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/common.cpp.s
.PHONY : src/common.cpp.s

src/cost.o: src/cost.cpp.o
.PHONY : src/cost.o

# target to build an object file
src/cost.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/cost.cpp.o
.PHONY : src/cost.cpp.o

src/cost.i: src/cost.cpp.i
.PHONY : src/cost.i

# target to preprocess a source file
src/cost.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/cost.cpp.i
.PHONY : src/cost.cpp.i

src/cost.s: src/cost.cpp.s
.PHONY : src/cost.s

# target to generate assembly for a file
src/cost.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/cost.cpp.s
.PHONY : src/cost.cpp.s

src/data_transfer_cpu.o: src/data_transfer_cpu.cpp.o
.PHONY : src/data_transfer_cpu.o

# target to build an object file
src/data_transfer_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/data_transfer_cpu.cpp.o
.PHONY : src/data_transfer_cpu.cpp.o

src/data_transfer_cpu.i: src/data_transfer_cpu.cpp.i
.PHONY : src/data_transfer_cpu.i

# target to preprocess a source file
src/data_transfer_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/data_transfer_cpu.cpp.i
.PHONY : src/data_transfer_cpu.cpp.i

src/data_transfer_cpu.s: src/data_transfer_cpu.cpp.s
.PHONY : src/data_transfer_cpu.s

# target to generate assembly for a file
src/data_transfer_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/data_transfer_cpu.cpp.s
.PHONY : src/data_transfer_cpu.cpp.s

src/dataloader.o: src/dataloader.cpp.o
.PHONY : src/dataloader.o

# target to build an object file
src/dataloader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/dataloader.cpp.o
.PHONY : src/dataloader.cpp.o

src/dataloader.i: src/dataloader.cpp.i
.PHONY : src/dataloader.i

# target to preprocess a source file
src/dataloader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/dataloader.cpp.i
.PHONY : src/dataloader.cpp.i

src/dataloader.s: src/dataloader.cpp.s
.PHONY : src/dataloader.s

# target to generate assembly for a file
src/dataloader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/dataloader.cpp.s
.PHONY : src/dataloader.cpp.s

src/derivative_calcul_cpu.o: src/derivative_calcul_cpu.cpp.o
.PHONY : src/derivative_calcul_cpu.o

# target to build an object file
src/derivative_calcul_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/derivative_calcul_cpu.cpp.o
.PHONY : src/derivative_calcul_cpu.cpp.o

src/derivative_calcul_cpu.i: src/derivative_calcul_cpu.cpp.i
.PHONY : src/derivative_calcul_cpu.i

# target to preprocess a source file
src/derivative_calcul_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/derivative_calcul_cpu.cpp.i
.PHONY : src/derivative_calcul_cpu.cpp.i

src/derivative_calcul_cpu.s: src/derivative_calcul_cpu.cpp.s
.PHONY : src/derivative_calcul_cpu.s

# target to generate assembly for a file
src/derivative_calcul_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/derivative_calcul_cpu.cpp.s
.PHONY : src/derivative_calcul_cpu.cpp.s

src/fc_layer_cpu.o: src/fc_layer_cpu.cpp.o
.PHONY : src/fc_layer_cpu.o

# target to build an object file
src/fc_layer_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/fc_layer_cpu.cpp.o
.PHONY : src/fc_layer_cpu.cpp.o

src/fc_layer_cpu.i: src/fc_layer_cpu.cpp.i
.PHONY : src/fc_layer_cpu.i

# target to preprocess a source file
src/fc_layer_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/fc_layer_cpu.cpp.i
.PHONY : src/fc_layer_cpu.cpp.i

src/fc_layer_cpu.s: src/fc_layer_cpu.cpp.s
.PHONY : src/fc_layer_cpu.s

# target to generate assembly for a file
src/fc_layer_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/fc_layer_cpu.cpp.s
.PHONY : src/fc_layer_cpu.cpp.s

src/feature_availability.o: src/feature_availability.cpp.o
.PHONY : src/feature_availability.o

# target to build an object file
src/feature_availability.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/feature_availability.cpp.o
.PHONY : src/feature_availability.cpp.o

src/feature_availability.i: src/feature_availability.cpp.i
.PHONY : src/feature_availability.i

# target to preprocess a source file
src/feature_availability.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/feature_availability.cpp.i
.PHONY : src/feature_availability.cpp.i

src/feature_availability.s: src/feature_availability.cpp.s
.PHONY : src/feature_availability.s

# target to generate assembly for a file
src/feature_availability.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/feature_availability.cpp.s
.PHONY : src/feature_availability.cpp.s

src/feed_forward_cpu.o: src/feed_forward_cpu.cpp.o
.PHONY : src/feed_forward_cpu.o

# target to build an object file
src/feed_forward_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/feed_forward_cpu.cpp.o
.PHONY : src/feed_forward_cpu.cpp.o

src/feed_forward_cpu.i: src/feed_forward_cpu.cpp.i
.PHONY : src/feed_forward_cpu.i

# target to preprocess a source file
src/feed_forward_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/feed_forward_cpu.cpp.i
.PHONY : src/feed_forward_cpu.cpp.i

src/feed_forward_cpu.s: src/feed_forward_cpu.cpp.s
.PHONY : src/feed_forward_cpu.s

# target to generate assembly for a file
src/feed_forward_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/feed_forward_cpu.cpp.s
.PHONY : src/feed_forward_cpu.cpp.s

src/global_param_update_cpu.o: src/global_param_update_cpu.cpp.o
.PHONY : src/global_param_update_cpu.o

# target to build an object file
src/global_param_update_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/global_param_update_cpu.cpp.o
.PHONY : src/global_param_update_cpu.cpp.o

src/global_param_update_cpu.i: src/global_param_update_cpu.cpp.i
.PHONY : src/global_param_update_cpu.i

# target to preprocess a source file
src/global_param_update_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/global_param_update_cpu.cpp.i
.PHONY : src/global_param_update_cpu.cpp.i

src/global_param_update_cpu.s: src/global_param_update_cpu.cpp.s
.PHONY : src/global_param_update_cpu.s

# target to generate assembly for a file
src/global_param_update_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/global_param_update_cpu.cpp.s
.PHONY : src/global_param_update_cpu.cpp.s

src/indices.o: src/indices.cpp.o
.PHONY : src/indices.o

# target to build an object file
src/indices.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/indices.cpp.o
.PHONY : src/indices.cpp.o

src/indices.i: src/indices.cpp.i
.PHONY : src/indices.i

# target to preprocess a source file
src/indices.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/indices.cpp.i
.PHONY : src/indices.cpp.i

src/indices.s: src/indices.cpp.s
.PHONY : src/indices.s

# target to generate assembly for a file
src/indices.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/indices.cpp.s
.PHONY : src/indices.cpp.s

src/lstm_feed_backward_cpu.o: src/lstm_feed_backward_cpu.cpp.o
.PHONY : src/lstm_feed_backward_cpu.o

# target to build an object file
src/lstm_feed_backward_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/lstm_feed_backward_cpu.cpp.o
.PHONY : src/lstm_feed_backward_cpu.cpp.o

src/lstm_feed_backward_cpu.i: src/lstm_feed_backward_cpu.cpp.i
.PHONY : src/lstm_feed_backward_cpu.i

# target to preprocess a source file
src/lstm_feed_backward_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/lstm_feed_backward_cpu.cpp.i
.PHONY : src/lstm_feed_backward_cpu.cpp.i

src/lstm_feed_backward_cpu.s: src/lstm_feed_backward_cpu.cpp.s
.PHONY : src/lstm_feed_backward_cpu.s

# target to generate assembly for a file
src/lstm_feed_backward_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/lstm_feed_backward_cpu.cpp.s
.PHONY : src/lstm_feed_backward_cpu.cpp.s

src/lstm_feed_forward_cpu.o: src/lstm_feed_forward_cpu.cpp.o
.PHONY : src/lstm_feed_forward_cpu.o

# target to build an object file
src/lstm_feed_forward_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/lstm_feed_forward_cpu.cpp.o
.PHONY : src/lstm_feed_forward_cpu.cpp.o

src/lstm_feed_forward_cpu.i: src/lstm_feed_forward_cpu.cpp.i
.PHONY : src/lstm_feed_forward_cpu.i

# target to preprocess a source file
src/lstm_feed_forward_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/lstm_feed_forward_cpu.cpp.i
.PHONY : src/lstm_feed_forward_cpu.cpp.i

src/lstm_feed_forward_cpu.s: src/lstm_feed_forward_cpu.cpp.s
.PHONY : src/lstm_feed_forward_cpu.s

# target to generate assembly for a file
src/lstm_feed_forward_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/lstm_feed_forward_cpu.cpp.s
.PHONY : src/lstm_feed_forward_cpu.cpp.s

src/net_init.o: src/net_init.cpp.o
.PHONY : src/net_init.o

# target to build an object file
src/net_init.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/net_init.cpp.o
.PHONY : src/net_init.cpp.o

src/net_init.i: src/net_init.cpp.i
.PHONY : src/net_init.i

# target to preprocess a source file
src/net_init.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/net_init.cpp.i
.PHONY : src/net_init.cpp.i

src/net_init.s: src/net_init.cpp.s
.PHONY : src/net_init.s

# target to generate assembly for a file
src/net_init.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/net_init.cpp.s
.PHONY : src/net_init.cpp.s

src/net_prop.o: src/net_prop.cpp.o
.PHONY : src/net_prop.o

# target to build an object file
src/net_prop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/net_prop.cpp.o
.PHONY : src/net_prop.cpp.o

src/net_prop.i: src/net_prop.cpp.i
.PHONY : src/net_prop.i

# target to preprocess a source file
src/net_prop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/net_prop.cpp.i
.PHONY : src/net_prop.cpp.i

src/net_prop.s: src/net_prop.cpp.s
.PHONY : src/net_prop.s

# target to generate assembly for a file
src/net_prop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/net_prop.cpp.s
.PHONY : src/net_prop.cpp.s

src/param_feed_backward_cpu.o: src/param_feed_backward_cpu.cpp.o
.PHONY : src/param_feed_backward_cpu.o

# target to build an object file
src/param_feed_backward_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/param_feed_backward_cpu.cpp.o
.PHONY : src/param_feed_backward_cpu.cpp.o

src/param_feed_backward_cpu.i: src/param_feed_backward_cpu.cpp.i
.PHONY : src/param_feed_backward_cpu.i

# target to preprocess a source file
src/param_feed_backward_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/param_feed_backward_cpu.cpp.i
.PHONY : src/param_feed_backward_cpu.cpp.i

src/param_feed_backward_cpu.s: src/param_feed_backward_cpu.cpp.s
.PHONY : src/param_feed_backward_cpu.s

# target to generate assembly for a file
src/param_feed_backward_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/param_feed_backward_cpu.cpp.s
.PHONY : src/param_feed_backward_cpu.cpp.s

src/python_api_cpu.o: src/python_api_cpu.cpp.o
.PHONY : src/python_api_cpu.o

# target to build an object file
src/python_api_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi.dir/build.make CMakeFiles/cutagi.dir/src/python_api_cpu.cpp.o
.PHONY : src/python_api_cpu.cpp.o

src/python_api_cpu.i: src/python_api_cpu.cpp.i
.PHONY : src/python_api_cpu.i

# target to preprocess a source file
src/python_api_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi.dir/build.make CMakeFiles/cutagi.dir/src/python_api_cpu.cpp.i
.PHONY : src/python_api_cpu.cpp.i

src/python_api_cpu.s: src/python_api_cpu.cpp.s
.PHONY : src/python_api_cpu.s

# target to generate assembly for a file
src/python_api_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi.dir/build.make CMakeFiles/cutagi.dir/src/python_api_cpu.cpp.s
.PHONY : src/python_api_cpu.cpp.s

src/self_attention_cpu.o: src/self_attention_cpu.cpp.o
.PHONY : src/self_attention_cpu.o

# target to build an object file
src/self_attention_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/self_attention_cpu.cpp.o
.PHONY : src/self_attention_cpu.cpp.o

src/self_attention_cpu.i: src/self_attention_cpu.cpp.i
.PHONY : src/self_attention_cpu.i

# target to preprocess a source file
src/self_attention_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/self_attention_cpu.cpp.i
.PHONY : src/self_attention_cpu.cpp.i

src/self_attention_cpu.s: src/self_attention_cpu.cpp.s
.PHONY : src/self_attention_cpu.s

# target to generate assembly for a file
src/self_attention_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/self_attention_cpu.cpp.s
.PHONY : src/self_attention_cpu.cpp.s

src/state_feed_backward_cpu.o: src/state_feed_backward_cpu.cpp.o
.PHONY : src/state_feed_backward_cpu.o

# target to build an object file
src/state_feed_backward_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/state_feed_backward_cpu.cpp.o
.PHONY : src/state_feed_backward_cpu.cpp.o

src/state_feed_backward_cpu.i: src/state_feed_backward_cpu.cpp.i
.PHONY : src/state_feed_backward_cpu.i

# target to preprocess a source file
src/state_feed_backward_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/state_feed_backward_cpu.cpp.i
.PHONY : src/state_feed_backward_cpu.cpp.i

src/state_feed_backward_cpu.s: src/state_feed_backward_cpu.cpp.s
.PHONY : src/state_feed_backward_cpu.s

# target to generate assembly for a file
src/state_feed_backward_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/state_feed_backward_cpu.cpp.s
.PHONY : src/state_feed_backward_cpu.cpp.s

src/struct_var.o: src/struct_var.cpp.o
.PHONY : src/struct_var.o

# target to build an object file
src/struct_var.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/struct_var.cpp.o
.PHONY : src/struct_var.cpp.o

src/struct_var.i: src/struct_var.cpp.i
.PHONY : src/struct_var.i

# target to preprocess a source file
src/struct_var.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/struct_var.cpp.i
.PHONY : src/struct_var.cpp.i

src/struct_var.s: src/struct_var.cpp.s
.PHONY : src/struct_var.s

# target to generate assembly for a file
src/struct_var.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/struct_var.cpp.s
.PHONY : src/struct_var.cpp.s

src/tagi_network_base.o: src/tagi_network_base.cpp.o
.PHONY : src/tagi_network_base.o

# target to build an object file
src/tagi_network_base.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/tagi_network_base.cpp.o
.PHONY : src/tagi_network_base.cpp.o

src/tagi_network_base.i: src/tagi_network_base.cpp.i
.PHONY : src/tagi_network_base.i

# target to preprocess a source file
src/tagi_network_base.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/tagi_network_base.cpp.i
.PHONY : src/tagi_network_base.cpp.i

src/tagi_network_base.s: src/tagi_network_base.cpp.s
.PHONY : src/tagi_network_base.s

# target to generate assembly for a file
src/tagi_network_base.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/tagi_network_base.cpp.s
.PHONY : src/tagi_network_base.cpp.s

src/tagi_network_cpu.o: src/tagi_network_cpu.cpp.o
.PHONY : src/tagi_network_cpu.o

# target to build an object file
src/tagi_network_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/tagi_network_cpu.cpp.o
.PHONY : src/tagi_network_cpu.cpp.o

src/tagi_network_cpu.i: src/tagi_network_cpu.cpp.i
.PHONY : src/tagi_network_cpu.i

# target to preprocess a source file
src/tagi_network_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/tagi_network_cpu.cpp.i
.PHONY : src/tagi_network_cpu.cpp.i

src/tagi_network_cpu.s: src/tagi_network_cpu.cpp.s
.PHONY : src/tagi_network_cpu.s

# target to generate assembly for a file
src/tagi_network_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/tagi_network_cpu.cpp.s
.PHONY : src/tagi_network_cpu.cpp.s

src/task_cpu.o: src/task_cpu.cpp.o
.PHONY : src/task_cpu.o

# target to build an object file
src/task_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/task_cpu.cpp.o
.PHONY : src/task_cpu.cpp.o

src/task_cpu.i: src/task_cpu.cpp.i
.PHONY : src/task_cpu.i

# target to preprocess a source file
src/task_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/task_cpu.cpp.i
.PHONY : src/task_cpu.cpp.i

src/task_cpu.s: src/task_cpu.cpp.s
.PHONY : src/task_cpu.s

# target to generate assembly for a file
src/task_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/task_cpu.cpp.s
.PHONY : src/task_cpu.cpp.s

src/user_input.o: src/user_input.cpp.o
.PHONY : src/user_input.o

# target to build an object file
src/user_input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/user_input.cpp.o
.PHONY : src/user_input.cpp.o

src/user_input.i: src/user_input.cpp.i
.PHONY : src/user_input.i

# target to preprocess a source file
src/user_input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/user_input.cpp.i
.PHONY : src/user_input.cpp.i

src/user_input.s: src/user_input.cpp.s
.PHONY : src/user_input.s

# target to generate assembly for a file
src/user_input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/user_input.cpp.s
.PHONY : src/user_input.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

test/act_func/test_act_func_cpu.o: test/act_func/test_act_func_cpu.cpp.o
.PHONY : test/act_func/test_act_func_cpu.o

# target to build an object file
test/act_func/test_act_func_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/act_func/test_act_func_cpu.cpp.o
.PHONY : test/act_func/test_act_func_cpu.cpp.o

test/act_func/test_act_func_cpu.i: test/act_func/test_act_func_cpu.cpp.i
.PHONY : test/act_func/test_act_func_cpu.i

# target to preprocess a source file
test/act_func/test_act_func_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/act_func/test_act_func_cpu.cpp.i
.PHONY : test/act_func/test_act_func_cpu.cpp.i

test/act_func/test_act_func_cpu.s: test/act_func/test_act_func_cpu.cpp.s
.PHONY : test/act_func/test_act_func_cpu.s

# target to generate assembly for a file
test/act_func/test_act_func_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/act_func/test_act_func_cpu.cpp.s
.PHONY : test/act_func/test_act_func_cpu.cpp.s

test/fnn/test_fnn_cpu.o: test/fnn/test_fnn_cpu.cpp.o
.PHONY : test/fnn/test_fnn_cpu.o

# target to build an object file
test/fnn/test_fnn_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/fnn/test_fnn_cpu.cpp.o
.PHONY : test/fnn/test_fnn_cpu.cpp.o

test/fnn/test_fnn_cpu.i: test/fnn/test_fnn_cpu.cpp.i
.PHONY : test/fnn/test_fnn_cpu.i

# target to preprocess a source file
test/fnn/test_fnn_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/fnn/test_fnn_cpu.cpp.i
.PHONY : test/fnn/test_fnn_cpu.cpp.i

test/fnn/test_fnn_cpu.s: test/fnn/test_fnn_cpu.cpp.s
.PHONY : test/fnn/test_fnn_cpu.s

# target to generate assembly for a file
test/fnn/test_fnn_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/fnn/test_fnn_cpu.cpp.s
.PHONY : test/fnn/test_fnn_cpu.cpp.s

test/fnn_derivatives/test_fnn_derivatives_cpu.o: test/fnn_derivatives/test_fnn_derivatives_cpu.cpp.o
.PHONY : test/fnn_derivatives/test_fnn_derivatives_cpu.o

# target to build an object file
test/fnn_derivatives/test_fnn_derivatives_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/fnn_derivatives/test_fnn_derivatives_cpu.cpp.o
.PHONY : test/fnn_derivatives/test_fnn_derivatives_cpu.cpp.o

test/fnn_derivatives/test_fnn_derivatives_cpu.i: test/fnn_derivatives/test_fnn_derivatives_cpu.cpp.i
.PHONY : test/fnn_derivatives/test_fnn_derivatives_cpu.i

# target to preprocess a source file
test/fnn_derivatives/test_fnn_derivatives_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/fnn_derivatives/test_fnn_derivatives_cpu.cpp.i
.PHONY : test/fnn_derivatives/test_fnn_derivatives_cpu.cpp.i

test/fnn_derivatives/test_fnn_derivatives_cpu.s: test/fnn_derivatives/test_fnn_derivatives_cpu.cpp.s
.PHONY : test/fnn_derivatives/test_fnn_derivatives_cpu.s

# target to generate assembly for a file
test/fnn_derivatives/test_fnn_derivatives_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/fnn_derivatives/test_fnn_derivatives_cpu.cpp.s
.PHONY : test/fnn_derivatives/test_fnn_derivatives_cpu.cpp.s

test/fnn_full_cov/test_fnn_full_cov_cpu.o: test/fnn_full_cov/test_fnn_full_cov_cpu.cpp.o
.PHONY : test/fnn_full_cov/test_fnn_full_cov_cpu.o

# target to build an object file
test/fnn_full_cov/test_fnn_full_cov_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/fnn_full_cov/test_fnn_full_cov_cpu.cpp.o
.PHONY : test/fnn_full_cov/test_fnn_full_cov_cpu.cpp.o

test/fnn_full_cov/test_fnn_full_cov_cpu.i: test/fnn_full_cov/test_fnn_full_cov_cpu.cpp.i
.PHONY : test/fnn_full_cov/test_fnn_full_cov_cpu.i

# target to preprocess a source file
test/fnn_full_cov/test_fnn_full_cov_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/fnn_full_cov/test_fnn_full_cov_cpu.cpp.i
.PHONY : test/fnn_full_cov/test_fnn_full_cov_cpu.cpp.i

test/fnn_full_cov/test_fnn_full_cov_cpu.s: test/fnn_full_cov/test_fnn_full_cov_cpu.cpp.s
.PHONY : test/fnn_full_cov/test_fnn_full_cov_cpu.s

# target to generate assembly for a file
test/fnn_full_cov/test_fnn_full_cov_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/fnn_full_cov/test_fnn_full_cov_cpu.cpp.s
.PHONY : test/fnn_full_cov/test_fnn_full_cov_cpu.cpp.s

test/fnn_heteros/test_fnn_heteros_cpu.o: test/fnn_heteros/test_fnn_heteros_cpu.cpp.o
.PHONY : test/fnn_heteros/test_fnn_heteros_cpu.o

# target to build an object file
test/fnn_heteros/test_fnn_heteros_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/fnn_heteros/test_fnn_heteros_cpu.cpp.o
.PHONY : test/fnn_heteros/test_fnn_heteros_cpu.cpp.o

test/fnn_heteros/test_fnn_heteros_cpu.i: test/fnn_heteros/test_fnn_heteros_cpu.cpp.i
.PHONY : test/fnn_heteros/test_fnn_heteros_cpu.i

# target to preprocess a source file
test/fnn_heteros/test_fnn_heteros_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/fnn_heteros/test_fnn_heteros_cpu.cpp.i
.PHONY : test/fnn_heteros/test_fnn_heteros_cpu.cpp.i

test/fnn_heteros/test_fnn_heteros_cpu.s: test/fnn_heteros/test_fnn_heteros_cpu.cpp.s
.PHONY : test/fnn_heteros/test_fnn_heteros_cpu.s

# target to generate assembly for a file
test/fnn_heteros/test_fnn_heteros_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/fnn_heteros/test_fnn_heteros_cpu.cpp.s
.PHONY : test/fnn_heteros/test_fnn_heteros_cpu.cpp.s

test/lstm/test_lstm_cpu.o: test/lstm/test_lstm_cpu.cpp.o
.PHONY : test/lstm/test_lstm_cpu.o

# target to build an object file
test/lstm/test_lstm_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/lstm/test_lstm_cpu.cpp.o
.PHONY : test/lstm/test_lstm_cpu.cpp.o

test/lstm/test_lstm_cpu.i: test/lstm/test_lstm_cpu.cpp.i
.PHONY : test/lstm/test_lstm_cpu.i

# target to preprocess a source file
test/lstm/test_lstm_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/lstm/test_lstm_cpu.cpp.i
.PHONY : test/lstm/test_lstm_cpu.cpp.i

test/lstm/test_lstm_cpu.s: test/lstm/test_lstm_cpu.cpp.s
.PHONY : test/lstm/test_lstm_cpu.s

# target to generate assembly for a file
test/lstm/test_lstm_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/lstm/test_lstm_cpu.cpp.s
.PHONY : test/lstm/test_lstm_cpu.cpp.s

test/mha/test_mha_cpu.o: test/mha/test_mha_cpu.cpp.o
.PHONY : test/mha/test_mha_cpu.o

# target to build an object file
test/mha/test_mha_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/mha/test_mha_cpu.cpp.o
.PHONY : test/mha/test_mha_cpu.cpp.o

test/mha/test_mha_cpu.i: test/mha/test_mha_cpu.cpp.i
.PHONY : test/mha/test_mha_cpu.i

# target to preprocess a source file
test/mha/test_mha_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/mha/test_mha_cpu.cpp.i
.PHONY : test/mha/test_mha_cpu.cpp.i

test/mha/test_mha_cpu.s: test/mha/test_mha_cpu.cpp.s
.PHONY : test/mha/test_mha_cpu.s

# target to generate assembly for a file
test/mha/test_mha_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/mha/test_mha_cpu.cpp.s
.PHONY : test/mha/test_mha_cpu.cpp.s

test/test_cpu.o: test/test_cpu.cpp.o
.PHONY : test/test_cpu.o

# target to build an object file
test/test_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/test_cpu.cpp.o
.PHONY : test/test_cpu.cpp.o

test/test_cpu.i: test/test_cpu.cpp.i
.PHONY : test/test_cpu.i

# target to preprocess a source file
test/test_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/test_cpu.cpp.i
.PHONY : test/test_cpu.cpp.i

test/test_cpu.s: test/test_cpu.cpp.s
.PHONY : test/test_cpu.s

# target to generate assembly for a file
test/test_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/test_cpu.cpp.s
.PHONY : test/test_cpu.cpp.s

test/test_dataloader.o: test/test_dataloader.cpp.o
.PHONY : test/test_dataloader.o

# target to build an object file
test/test_dataloader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/test_dataloader.cpp.o
.PHONY : test/test_dataloader.cpp.o

test/test_dataloader.i: test/test_dataloader.cpp.i
.PHONY : test/test_dataloader.i

# target to preprocess a source file
test/test_dataloader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/test_dataloader.cpp.i
.PHONY : test/test_dataloader.cpp.i

test/test_dataloader.s: test/test_dataloader.cpp.s
.PHONY : test/test_dataloader.s

# target to generate assembly for a file
test/test_dataloader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/test_dataloader.cpp.s
.PHONY : test/test_dataloader.cpp.s

test/test_lstm.o: test/test_lstm.cpp.o
.PHONY : test/test_lstm.o

# target to build an object file
test/test_lstm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/test_lstm.cpp.o
.PHONY : test/test_lstm.cpp.o

test/test_lstm.i: test/test_lstm.cpp.i
.PHONY : test/test_lstm.i

# target to preprocess a source file
test/test_lstm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/test_lstm.cpp.i
.PHONY : test/test_lstm.cpp.i

test/test_lstm.s: test/test_lstm.cpp.s
.PHONY : test/test_lstm.s

# target to generate assembly for a file
test/test_lstm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/test_lstm.cpp.s
.PHONY : test/test_lstm.cpp.s

test/test_lstm_cpu.o: test/test_lstm_cpu.cpp.o
.PHONY : test/test_lstm_cpu.o

# target to build an object file
test/test_lstm_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/test_lstm_cpu.cpp.o
.PHONY : test/test_lstm_cpu.cpp.o

test/test_lstm_cpu.i: test/test_lstm_cpu.cpp.i
.PHONY : test/test_lstm_cpu.i

# target to preprocess a source file
test/test_lstm_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/test_lstm_cpu.cpp.i
.PHONY : test/test_lstm_cpu.cpp.i

test/test_lstm_cpu.s: test/test_lstm_cpu.cpp.s
.PHONY : test/test_lstm_cpu.s

# target to generate assembly for a file
test/test_lstm_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/test_lstm_cpu.cpp.s
.PHONY : test/test_lstm_cpu.cpp.s

test/test_regression.o: test/test_regression.cpp.o
.PHONY : test/test_regression.o

# target to build an object file
test/test_regression.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/test_regression.cpp.o
.PHONY : test/test_regression.cpp.o

test/test_regression.i: test/test_regression.cpp.i
.PHONY : test/test_regression.i

# target to preprocess a source file
test/test_regression.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/test_regression.cpp.i
.PHONY : test/test_regression.cpp.i

test/test_regression.s: test/test_regression.cpp.s
.PHONY : test/test_regression.s

# target to generate assembly for a file
test/test_regression.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cutagi_lib.dir/build.make CMakeFiles/cutagi_lib.dir/test/test_regression.cpp.s
.PHONY : test/test_regression.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cutagi"
	@echo "... cutagi_lib"
	@echo "... main"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/activation_fun_cpu.o"
	@echo "... src/activation_fun_cpu.i"
	@echo "... src/activation_fun_cpu.s"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/cost.o"
	@echo "... src/cost.i"
	@echo "... src/cost.s"
	@echo "... src/data_transfer_cpu.o"
	@echo "... src/data_transfer_cpu.i"
	@echo "... src/data_transfer_cpu.s"
	@echo "... src/dataloader.o"
	@echo "... src/dataloader.i"
	@echo "... src/dataloader.s"
	@echo "... src/derivative_calcul_cpu.o"
	@echo "... src/derivative_calcul_cpu.i"
	@echo "... src/derivative_calcul_cpu.s"
	@echo "... src/fc_layer_cpu.o"
	@echo "... src/fc_layer_cpu.i"
	@echo "... src/fc_layer_cpu.s"
	@echo "... src/feature_availability.o"
	@echo "... src/feature_availability.i"
	@echo "... src/feature_availability.s"
	@echo "... src/feed_forward_cpu.o"
	@echo "... src/feed_forward_cpu.i"
	@echo "... src/feed_forward_cpu.s"
	@echo "... src/global_param_update_cpu.o"
	@echo "... src/global_param_update_cpu.i"
	@echo "... src/global_param_update_cpu.s"
	@echo "... src/indices.o"
	@echo "... src/indices.i"
	@echo "... src/indices.s"
	@echo "... src/lstm_feed_backward_cpu.o"
	@echo "... src/lstm_feed_backward_cpu.i"
	@echo "... src/lstm_feed_backward_cpu.s"
	@echo "... src/lstm_feed_forward_cpu.o"
	@echo "... src/lstm_feed_forward_cpu.i"
	@echo "... src/lstm_feed_forward_cpu.s"
	@echo "... src/net_init.o"
	@echo "... src/net_init.i"
	@echo "... src/net_init.s"
	@echo "... src/net_prop.o"
	@echo "... src/net_prop.i"
	@echo "... src/net_prop.s"
	@echo "... src/param_feed_backward_cpu.o"
	@echo "... src/param_feed_backward_cpu.i"
	@echo "... src/param_feed_backward_cpu.s"
	@echo "... src/python_api_cpu.o"
	@echo "... src/python_api_cpu.i"
	@echo "... src/python_api_cpu.s"
	@echo "... src/self_attention_cpu.o"
	@echo "... src/self_attention_cpu.i"
	@echo "... src/self_attention_cpu.s"
	@echo "... src/state_feed_backward_cpu.o"
	@echo "... src/state_feed_backward_cpu.i"
	@echo "... src/state_feed_backward_cpu.s"
	@echo "... src/struct_var.o"
	@echo "... src/struct_var.i"
	@echo "... src/struct_var.s"
	@echo "... src/tagi_network_base.o"
	@echo "... src/tagi_network_base.i"
	@echo "... src/tagi_network_base.s"
	@echo "... src/tagi_network_cpu.o"
	@echo "... src/tagi_network_cpu.i"
	@echo "... src/tagi_network_cpu.s"
	@echo "... src/task_cpu.o"
	@echo "... src/task_cpu.i"
	@echo "... src/task_cpu.s"
	@echo "... src/user_input.o"
	@echo "... src/user_input.i"
	@echo "... src/user_input.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... test/act_func/test_act_func_cpu.o"
	@echo "... test/act_func/test_act_func_cpu.i"
	@echo "... test/act_func/test_act_func_cpu.s"
	@echo "... test/fnn/test_fnn_cpu.o"
	@echo "... test/fnn/test_fnn_cpu.i"
	@echo "... test/fnn/test_fnn_cpu.s"
	@echo "... test/fnn_derivatives/test_fnn_derivatives_cpu.o"
	@echo "... test/fnn_derivatives/test_fnn_derivatives_cpu.i"
	@echo "... test/fnn_derivatives/test_fnn_derivatives_cpu.s"
	@echo "... test/fnn_full_cov/test_fnn_full_cov_cpu.o"
	@echo "... test/fnn_full_cov/test_fnn_full_cov_cpu.i"
	@echo "... test/fnn_full_cov/test_fnn_full_cov_cpu.s"
	@echo "... test/fnn_heteros/test_fnn_heteros_cpu.o"
	@echo "... test/fnn_heteros/test_fnn_heteros_cpu.i"
	@echo "... test/fnn_heteros/test_fnn_heteros_cpu.s"
	@echo "... test/lstm/test_lstm_cpu.o"
	@echo "... test/lstm/test_lstm_cpu.i"
	@echo "... test/lstm/test_lstm_cpu.s"
	@echo "... test/mha/test_mha_cpu.o"
	@echo "... test/mha/test_mha_cpu.i"
	@echo "... test/mha/test_mha_cpu.s"
	@echo "... test/test_cpu.o"
	@echo "... test/test_cpu.i"
	@echo "... test/test_cpu.s"
	@echo "... test/test_dataloader.o"
	@echo "... test/test_dataloader.i"
	@echo "... test/test_dataloader.s"
	@echo "... test/test_lstm.o"
	@echo "... test/test_lstm.i"
	@echo "... test/test_lstm.s"
	@echo "... test/test_lstm_cpu.o"
	@echo "... test/test_lstm_cpu.i"
	@echo "... test/test_lstm_cpu.s"
	@echo "... test/test_regression.o"
	@echo "... test/test_regression.i"
	@echo "... test/test_regression.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

